In [1]:
import pandas as pd

In [2]:
bond = pd.read_csv("jamesbond.csv")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [11]:
bond.where(bond["Box Office"] > 500)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,The Spy Who Loved Me,1977.0,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979.0,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,GoldenEye,1995.0,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Casino Royale,2006.0,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008.0,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012.0,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015.0,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [13]:
bond.mask(bond["Box Office"] > 500)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Casino Royale,1967.0,David Niven,Ken Hughes,315.0,85.0,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,On Her Majesty's Secret Service,1969.0,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973.0,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974.0,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,For Your Eyes Only,1981.0,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983.0,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985.0,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987.0,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989.0,Timothy Dalton,John Glen,250.9,56.7,7.9
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Tomorrow Never Dies,1997.0,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999.0,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002.0,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## set_index / reset_index

In [15]:
bond[["Film", "Year"]]

                               Film  Year
0                            Dr. No  1962
1             From Russia with Love  1963
2                        Goldfinger  1964
3                       Thunderball  1965
4                     Casino Royale  1967
5               You Only Live Twice  1967
6   On Her Majesty's Secret Service  1969
7              Diamonds Are Forever  1971
8                  Live and Let Die  1973
9       The Man with the Golden Gun  1974
10             The Spy Who Loved Me  1977
11                        Moonraker  1979
12               For Your Eyes Only  1981
13            Never Say Never Again  1983
14                        Octopussy  1983
15                 A View to a Kill  1985
16             The Living Daylights  1987
17                  Licence to Kill  1989
18                        GoldenEye  1995
19              Tomorrow Never Dies  1997
20          The World Is Not Enough  1999
21                  Die Another Day  2002
22                    Casino Royale  2006
23                Quantum of Solace  2008
24                          Skyfall  2012
25                          Spectre  2015

In [33]:
bond["Film"][0:5]

0                   Dr. No
1    From Russia with Love
2               Goldfinger
3              Thunderball
4            Casino Royale
Name: Film, dtype: object

In [85]:
bond.set_index(keys = "Film", inplace = True)

In [18]:
bond.reset_index(drop = False, inplace = True)

In [20]:
bond.head(3)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

### Retrive rows by Index Label .loc[ ]

In [35]:
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [87]:
bond.set_index(keys = "Film", inplace = True)
bond.sort_index(inplace = True)
bond.head()

KeyError: "None of ['Film'] are in the columns"

In [37]:
bond.loc["Die Another Day"]

Year                           2002
Actor                Pierce Brosnan
Director               Lee Tamahori
Box Office                    465.4
Budget                        154.2
Bond Actor Salary              17.9
Name: Die Another Day, dtype: object

In [38]:
bond.loc[["Casino Royale", "Die Another Day"]]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [43]:
bond.loc["Die Another Day":"Goldfinger"]
#bond.loc["Goldfinger"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [44]:
bond.loc[:"Goldfinger"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [45]:
bond.loc["Goldfinger", "Actor"]

'Sean Connery'

In [49]:
bond.loc["Casino Royale", "Actor"]

Film
Casino Royale    Daniel Craig
Casino Royale     David Niven
Name: Actor, dtype: object

In [51]:
bond.loc["Goldfinger":, ["Actor", "Director", "Year"]]

                                          Actor            Director  Year
Film
Goldfinger                         Sean Connery        Guy Hamilton  1964
Licence to Kill                  Timothy Dalton           John Glen  1989
Live and Let Die                    Roger Moore        Guy Hamilton  1973
Moonraker                           Roger Moore       Lewis Gilbert  1979
Never Say Never Again              Sean Connery      Irvin Kershner  1983
Octopussy                           Roger Moore           John Glen  1983
On Her Majesty's Secret Service  George Lazenby       Peter R. Hunt  1969
Quantum of Solace                  Daniel Craig        Marc Forster  2008
Skyfall                            Daniel Craig          Sam Mendes  2012
Spectre                            Daniel Craig          Sam Mendes  2015
The Living Daylights             Timothy Dalton           John Glen  1987
The Man with the Golden Gun         Roger Moore        Guy Hamilton  1974
The Spy Who Loved Me                Roger Moore       Lewis Gilbert  1977
The World Is Not Enough          Pierce Brosnan       Michael Apted  1999
Thunderball                        Sean Connery       Terence Young  1965
Tomorrow Never Dies              Pierce Brosnan  Roger Spottiswoode  1997
You Only Live Twice                Sean Connery       Lewis Gilbert  1967

In [52]:
bond.loc[:,:]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [53]:
bond.iloc[0]

Year                        1985
Actor                Roger Moore
Director               John Glen
Box Office                 275.2
Budget                      54.5
Bond Actor Salary            9.1
Name: A View to a Kill, dtype: object

In [54]:
bond.iloc[:5, 1:]

,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [62]:
bond.loc["Goldfinger", "Actor"] = "Sean Connery"

In [57]:
bond.loc["Goldfinger", "Actor"]

'Sir Sean Connery'

In [58]:
bond.loc["Goldfinger"]

Year                             1964
Actor                Sir Sean Connery
Director                 Guy Hamilton
Box Office                      820.4
Budget                           18.6
Bond Actor Salary                 3.2
Name: Goldfinger, dtype: object

In [70]:
actor_sean_connery = bond["Actor"] == "Sean Connery"

In [73]:
bond.loc[actor_sean_connery, "Actor"] = "Sir Sean Connery"

In [74]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

### Rename Index and Columns

In [88]:
bond.sort_index(inplace = True)

In [89]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [90]:
bond.rename(mapper = {"Goldfinger": "Gold Finger",
                     "GoldenEye": "Golden Eye"}, axis = 0)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Gold Finger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [100]:
mapper = {i: i+" test" for i in bond.index}
print(mapper)
bond.rename(mapper = mapper, axis = "rows")

{'A View to a Kill': 'A View to a Kill test', 'Casino Royale': 'Casino Royale test', 'Diamonds Are Forever': 'Diamonds Are Forever test', 'Die Another Day': 'Die Another Day test', 'Dr. No': 'Dr. No test', 'For Your Eyes Only': 'For Your Eyes Only test', 'From Russia with Love': 'From Russia with Love test', 'GoldenEye': 'GoldenEye test', 'Goldfinger': 'Goldfinger test', 'Licence to Kill': 'Licence to Kill test', 'Live and Let Die': 'Live and Let Die test', 'Moonraker': 'Moonraker test', 'Never Say Never Again': 'Never Say Never Again test', 'Octopussy': 'Octopussy test', "On Her Majesty's Secret Service": "On Her Majesty's Secret Service test", 'Quantum of Solace': 'Quantum of Solace test', 'Skyfall': 'Skyfall test', 'Spectre': 'Spectre test', 'The Living Daylights': 'The Living Daylights test', 'The Man with the Golden Gun': 'The Man with the Golden Gun test', 'The Spy Who Loved Me': 'The Spy Who Loved Me test', 'The World Is Not Enough': 'The World Is Not Enough test', 'Thunderball': 'Thunderball test', 'Tomorrow Never Dies': 'Tomorrow Never Dies test', 'You Only Live Twice': 'You Only Live Twice test'}

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill test,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale test,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale test,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever test,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day test,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No test,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only test,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love test,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye test,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger test,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill test,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die test,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker test,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again test,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy test,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service test,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace test,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall test,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre test,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights test,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun test,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me test,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough test,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball test,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies test,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice test,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [102]:
bond.rename(index = mapper)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill test,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale test,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale test,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever test,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day test,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No test,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only test,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love test,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye test,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger test,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill test,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die test,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker test,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again test,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy test,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service test,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace test,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall test,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre test,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights test,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun test,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me test,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough test,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball test,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies test,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice test,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [103]:
bond.rename (mapper = {"Year": "Release Year", "Box Office" : "Revenue"}, axis = 1)

,Release Year,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [105]:
bond.rename (columns = {"Year": "Release Year", "Box Office" : "Revenue"})

,Release Year,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

### Delete Rows and Columns

In [31]:
bond = pd.read_csv("jamesbond.csv", index_col = "Film")
bond.sort_index(inplace = True)

In [4]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [116]:
roger = bond["Actor"] == "Roger Moore"
bond.drop(labels = bond[roger].index)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [117]:
bond.drop(labels = "Year", axis = 1)

,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

### Random Sample

In [118]:
bond.sample()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [119]:
bond.sample(n =5)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8

In [120]:
bond.sample(frac = .3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [5]:
bond.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [11]:
bond.nlargest(n = 3, columns = "Budget", keep = 'last')

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5

In [13]:
bond.nlargest(n = 3, columns = ["Budget", "Box Office"])

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5

In [15]:
bond.nsmallest(n =3 , columns = "Box Office")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

In [19]:
bond.where((bond["Actor"] == "Roger Moore") & (bond["Year"] > 1980))

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985.0,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,NaN,NaN,NaN,NaN,NaN,NaN
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,NaN,NaN,NaN,NaN,NaN,NaN
For Your Eyes Only,1981.0,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,NaN,NaN,NaN,NaN,NaN,NaN
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,NaN,NaN,NaN,NaN,NaN,NaN
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,1983.0,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,NaN,NaN,NaN,NaN,NaN,NaN
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
bond.query('Actor == "Roger Moore" and Year > 1980')

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8

In [25]:
directors = bond["Director"]

In [28]:
directors["A View to a Kill"] = "Mister John Glen"

C:\Users\Koushik\AppData\Local\Temp\ipykernel_14692\2347769033.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  directors["A View to a Kill"] = "Mister John Glen"

In [29]:
directors

Film
A View to a Kill                     Mister John Glen
Casino Royale                         Martin Campbell
Casino Royale                              Ken Hughes
Diamonds Are Forever                     Guy Hamilton
Die Another Day                          Lee Tamahori
Dr. No                                  Terence Young
For Your Eyes Only                          John Glen
From Russia with Love                   Terence Young
GoldenEye                             Martin Campbell
Goldfinger                               Guy Hamilton
Licence to Kill                             John Glen
Live and Let Die                         Guy Hamilton
Moonraker                               Lewis Gilbert
Never Say Never Again                  Irvin Kershner
Octopussy                                   John Glen
On Her Majesty's Secret Service         Peter R. Hunt
Quantum of Solace                        Marc Forster
Skyfall                                    Sam Mendes
Spectre                                    Sam Mendes
The Living Daylights                        John Glen
The Man with the Golden Gun              Guy Hamilton
The Spy Who Loved Me                    Lewis Gilbert
The World Is Not Enough                 Michael Apted
Thunderball                             Terence Young
Tomorrow Never Dies                Roger Spottiswoode
You Only Live Twice                     Lewis Gilbert
Name: Director, dtype: object

In [30]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,Mister John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [32]:
directors = bond["Director"].copy()

In [34]:
directors

Film
A View to a Kill                            John Glen
Casino Royale                         Martin Campbell
Casino Royale                              Ken Hughes
Diamonds Are Forever                     Guy Hamilton
Die Another Day                          Lee Tamahori
Dr. No                                  Terence Young
For Your Eyes Only                          John Glen
From Russia with Love                   Terence Young
GoldenEye                             Martin Campbell
Goldfinger                               Guy Hamilton
Licence to Kill                             John Glen
Live and Let Die                         Guy Hamilton
Moonraker                               Lewis Gilbert
Never Say Never Again                  Irvin Kershner
Octopussy                                   John Glen
On Her Majesty's Secret Service         Peter R. Hunt
Quantum of Solace                        Marc Forster
Skyfall                                    Sam Mendes
Spectre                                    Sam Mendes
The Living Daylights                        John Glen
The Man with the Golden Gun              Guy Hamilton
The Spy Who Loved Me                    Lewis Gilbert
The World Is Not Enough                 Michael Apted
Thunderball                             Terence Young
Tomorrow Never Dies                Roger Spottiswoode
You Only Live Twice                     Lewis Gilbert
Name: Director, dtype: object

In [36]:
directors["A View to a Kill"] = "Mister John Glen"

In [37]:
directors

Film
A View to a Kill                     Mister John Glen
Casino Royale                         Martin Campbell
Casino Royale                              Ken Hughes
Diamonds Are Forever                     Guy Hamilton
Die Another Day                          Lee Tamahori
Dr. No                                  Terence Young
For Your Eyes Only                          John Glen
From Russia with Love                   Terence Young
GoldenEye                             Martin Campbell
Goldfinger                               Guy Hamilton
Licence to Kill                             John Glen
Live and Let Die                         Guy Hamilton
Moonraker                               Lewis Gilbert
Never Say Never Again                  Irvin Kershner
Octopussy                                   John Glen
On Her Majesty's Secret Service         Peter R. Hunt
Quantum of Solace                        Marc Forster
Skyfall                                    Sam Mendes
Spectre                                    Sam Mendes
The Living Daylights                        John Glen
The Man with the Golden Gun              Guy Hamilton
The Spy Who Loved Me                    Lewis Gilbert
The World Is Not Enough                 Michael Apted
Thunderball                             Terence Young
Tomorrow Never Dies                Roger Spottiswoode
You Only Live Twice                     Lewis Gilbert
Name: Director, dtype: object

In [38]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [54]:
director = pd.read_csv("jamesbond.csv", usecols = ["Film", "Year"], index_col = "Year").squeeze()

In [55]:
director

Year
1962                             Dr. No
1963              From Russia with Love
1964                         Goldfinger
1965                        Thunderball
1967                      Casino Royale
1967                You Only Live Twice
1969    On Her Majesty's Secret Service
1971               Diamonds Are Forever
1973                   Live and Let Die
1974        The Man with the Golden Gun
1977               The Spy Who Loved Me
1979                          Moonraker
1981                 For Your Eyes Only
1983              Never Say Never Again
1983                          Octopussy
1985                   A View to a Kill
1987               The Living Daylights
1989                    Licence to Kill
1995                          GoldenEye
1997                Tomorrow Never Dies
1999            The World Is Not Enough
2002                    Die Another Day
2006                      Casino Royale
2008                  Quantum of Solace
2012                            Skyfall
2015                            Spectre
Name: Film, dtype: object